config/routes.rb
Rails.application.routes.draw do
  resources :phrases

  root 'phrases#index'

end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
	@last_phrase_index = -1

	def self.find_diff_phrase
		new_phrase_index = 0
		loop do
			new_phrase_index = Phrase.find(1 + rand(Phrase.all.count))
			break if (new_phrase_index.id != @last_phrase_index)
		end

		@last_phrase_index = new_phrase_index.id
		new_phrase_index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  before_action :set_phrase, only: [:show, :edit, :update, :destroy]
  
  # GET /phrases
  # GET /phrases.json
  def index
    @phrases = Phrase.all

    respond_to do |format|
      format.html { @phrases = Phrase.all }
      format.json { 
        render :json => Phrase.find_diff_phrase
      }
    end
  end

  # GET /phrases/1
  # GET /phrases/1.json
  def show
  end

  # GET /phrases/new
  def new
    @phrase = Phrase.new
  end

  # GET /phrases/1/edit
  def edit
  end

  # POST /phrases
  # POST /phrases.json
  def create
    @phrase = Phrase.new(phrase_params)

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to @phrase, notice: 'Phrase was successfully created.' }
        format.json { render :show, status: :created, location: @phrase }
      else
        format.html { render :new }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phrases/1
  # PATCH/PUT /phrases/1.json
  def update
    respond_to do |format|
      if @phrase.update(phrase_params)
        format.html { redirect_to @phrase, notice: 'Phrase was successfully updated.' }
        format.json { render :show, status: :ok, location: @phrase }
      else
        format.html { render :edit }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1
  # DELETE /phrases/1.json
  def destroy
    @phrase.destroy
    respond_to do |format|
      format.html { redirect_to phrases_url, notice: 'Phrase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phrase
      @phrase = Phrase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phrase_params
      params.require(:phrase).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodaysMottoWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phrases/_form.html.erb
<%= form_for(@phrase) do |f| %>
  <% if @phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
      <% @phrase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phrases/edit.html.erb
<h1>Editing phrase</h1>

<%= render 'form' %>

<%= link_to 'Show', @phrase %> |
<%= link_to 'Back', phrases_path %>

app/views/phrases/index.html.erb
<h1>Listing phrases</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phrases.each do |phrase| %>
      <tr>
        <td><%= phrase.text %></td>
        <td><%= link_to 'Show', phrase %></td>
        <td><%= link_to 'Edit', edit_phrase_path(phrase) %></td>
        <td><%= link_to 'Destroy', phrase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phrase', new_phrase_path %>

app/views/phrases/new.html.erb
<h1>New phrase</h1>

<%= render 'form' %>

<%= link_to 'Back', phrases_path %>

app/views/phrases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @phrase.text %>
</p>

<%= link_to 'Edit', edit_phrase_path(@phrase) %> |
<%= link_to 'Back', phrases_path %>